@baseUrl = http://localhost:3000


### AppController
# @name AppControllerGet
GET http://localhost:3000/

###AppController
# @name AppControllerGetExemple
GET  {{baseUrl}}/exemplo/

### ConceitosManualController
# @name ConceitosManualController
GET  {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoController
# @name ConceitosAutomaticoController
GET  {{baseUrl}}/conceitos-automatico