@baseUrl = http://localhost:3000

# Recados
###
GET {{baseUrl}}/recados

###
GET {{baseUrl}}/recados/10

### AppController
# @name AppControllerGet
GET http://localhost:3000/

###AppController
# @name AppControllerGetExemple
GET  {{baseUrl}}/exemplo/

### ConceitosManualController
# @name ConceitosManualController
GET  {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoController
# @name ConceitosAutomaticoController
GET  {{baseUrl}}/conceitos-automatico

### ConceitosManualService
# @name ConceitosManualService
GET  {{baseUrl}}/conceitos-manual/solution

### ConceitosAutomaticoService
# @name ConceitosAutomaticoService
GET  {{baseUrl}}/conceitos-automatico/solution

###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "recado": "este é o recado que estou enviando =)"
}

###
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
    "recado": "recado alterado",
    "atualizar": "true"
}

###
DELETE {{baseUrl}}/recados/2